export const HORSE_NAMES = [
  'Ada Lovelace',
  'Grace Hopper',
  'Margaret Hamilton',
  'Katherine Johnson',
  'Hedy Lamarr',
  'Joan Clarke',
  'Annie Easley',
  'Dorothy Vaughan',
  'Mary Jackson',
  'Radia Perlman',
  'Barbara Liskov',
  'Frances Allen',
  'Sister Mary Keller',
  'Adele Goldberg',
  'Karen Sparck Jones',
  'Shafi Goldwasser',
  'Fei-Fei Li',
  'Timnit Gebru',
  'Marissa Mayer',
  'Susan Wojcicki',
] as const

export const HORSE_COLORS = [
  '#EF5350',
  '#EC407A',
  '#AB47BC',
  '#7E57C2',
  '#5C6BC0',
  '#42A5F5',
  '#29B6F6',
  '#26C6DA',
  '#26A69A',
  '#66BB6A',
  '#9CCC65',
  '#D4E157',
  '#FFEE58',
  '#FFCA28',
  '#FFA726',
  '#FF7043',
  '#8D6E63',
  '#78909C',
  '#F06292',
  '#00ACC1',
] as const
